junit:
  stage: test
  script:
    - mvn -B clean test
generate_artifacts:
  stage: deploy
  script:
    - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64 mvn -B clean site package
  artifacts:
    paths:
    - target/s202group7.jar